name: Workflow
on: 
  push:
    branches:
      - pipe
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
         node-version: 18
      
      - name: Dependencies
        run: npm install
    
      - name: SC Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR}}
        with:
          args: |
            -Dsonar.projectKey=sebalvarezch_laboratorio-final
            -Dsonar.organization=sebalvarezch
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
