name: Workflow
on: 
  push:
    branches:
      - pipe
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
         node-version: 18
      
      - name: Dependencies
        run: npm install
    
      - name: SC Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR }}
        with:
          args: |
            -Dsonar.projectKey=sebalvarezch_laboratorio-final
            -Dsonar.organization=sebalvarezch
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=main

   #  - name: Chequeo de calidad
   #    uses: sonarsource/sonarqube-quality-gate-action@master
    #   env: 
    #     SONAR_TOKEN: ${{ secrets.SONAR }}

  SCA:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set java 
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Corriendo Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "laboratorio-final"
        path: "."
        format: "HTML"
        out: "dependency-check-report"

    - name: Fallo al encontrar vulnerabilidades
      run: |
        echo "Realizando analisis"
        grep -qE 'CRITICAL|HIGH|MEDIUM' dependency-check-report.html && {
        echo "vulnerabilidades encontradas de severidad critica, alta o media"
        exit 1
        } || {
        echo "No se encontraron vulnerabilidades"
        }
